#!/usr/bin/expect

set timeout -1

if { $argc != 5 } {
    puts "Usage $argv0 host user path pass file"
    exit 1
}

set host [lindex $argv 0]
set user [lindex $argv 1]
set path [lindex $argv 2]
set pass [lindex $argv 3]
set file [lindex $argv 4]

spawn scp $file $user@$host:$path
expect *assword:

send "$pass\r"
expect eof
